networks:
  openfga:


services:
  postgres:
    image: postgres:18
    container_name: postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # coturn:
  #   image: coturn/coturn:latest
  #   container_name: coturn
  #   ports:
  #     - "3478:3478"
  #     - "3478:3478/udp"
  #     - "49160-49200:49160-49200/udp"
  #   networks:
  #     - host
  #   volumes:
  #     - ./turnserver.conf:/etc/coturn/turnserver.conf
